// This file contains a basic redux slice
import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// count interface - shape
interface CounterState {
  value: number;
}

// initial state
const initialState: CounterState = {
  value: 0
} 

// slice that contains reducer logic
const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
    // increment one
    incremented(state) {
      // immer library(included in the redux toolkit) works under the hood 
      // to track changes to state and ensure state is 'immutable'
      state.value++
    },
    // decrement one
  }
})

// `actions` and `reducer` are not explicitly defined
// however they are generated by the createSlice() function
/**
 * The createSlice function generates an object that has two 
 * properties: actions and reducer. 
 * The actions property contains all the action creators generated by createSlice, 
 * while the reducer property contains the reducer function generated by createSlice 
 * based on the initialState and the reducers object provided in the configuration object
 * Therefore, when we export counterSlice.actions, we are exporting an object containing 
 * the incremented action creator. When we export counterSlice.reducer, we are exporting 
 * the reducer function generated by createSlice.
 */

export const { incremented } = counterSlice.actions;
export default counterSlice.reducer;
